package com.example.purrytify.models

import com.google.gson.annotations.SerializedName

data class OnlineSong(
    @SerializedName("id") val id: Int,
    @SerializedName("title") val title: String,
    @SerializedName("artist") val artist: String,
    @SerializedName("artwork") val artworkUrl: String,
    @SerializedName("url") val audioUrl: String,
    @SerializedName("duration") val durationString: String,
    @SerializedName("country") val country: String,
    @SerializedName("rank") val rank: Int,
    @SerializedName("createdAt") val createdAt: String,
    @SerializedName("updatedAt") val updatedAt: String
) {
    // Convert duration string (mm:ss) to milliseconds for compatibility with local songs
    fun getDurationInMillis(): Long {
        val parts = durationString.split(":")
        if (parts.size == 2) {
            val minutes = parts[0].toLongOrNull() ?: 0
            val seconds = parts[1].toLongOrNull() ?: 0
            return (minutes * 60 + seconds) * 1000
        }
        return 0
    }

    // Convert to local Song entity (for database)
    fun toSongEntity(): com.example.purrytify.data.entity.Song {
        return com.example.purrytify.data.entity.Song(
            id = 0, // ID will be auto-generated by Room
            title = title,
            artist = artist,
            artworkPath = artworkUrl,
            filePath = audioUrl,
            duration = getDurationInMillis(),
            isLiked = false,
            lastPlayed = null,
            addedAt = System.currentTimeMillis(),
            userId = -1, // Will be updated with current user ID
            isOnline = true,
            onlineId = id // Store the online ID reference
        )
    }
}